---
name: "tagged-release"

on:
  push:
    tags:
      - "r*"

jobs:
  publish-image:
    name: "Publish Docker Image to Docker Hub"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Push image
        run: |
          cd cassandra-4.0.6
          IMAGE_NAME=shotover/cassandra-test:4.0.6-${GITHUB_REF/refs\/tags\//}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

          cd ../cassandra-3.11.13
          IMAGE_NAME=shotover/cassandra-test:3.11.13-${GITHUB_REF/refs\/tags\//}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

          cd ../cassandra-5.0-rc1
          IMAGE_NAME=shotover/cassandra-test:5.0-rc1-${GITHUB_REF/refs\/tags\//}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
