---
name: "tagged-release"

on:
  push:
    tags:
      - "r*"

jobs:
  build-image:
    name: "Build ${{ matrix.cassandra }} (${{ matrix.runner }})"
    strategy:
      matrix:
        cassandra: ["4.0.6", "3.11.13", "5.0-rc1"]
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Login to Docker Hub
        uses: step-security/docker-login-action@6aa05fe688caf2c58e784663f01b3415ced503e8 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0
      - name: Build and push single-platform image
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          ARCH=$(dpkg --print-architecture)
          docker buildx build cassandra-${{ matrix.cassandra }} \
            -t shotover/cassandra-test:${{ matrix.cassandra }}-$TAG-$ARCH \
            --push

  publish-manifest:
    name: "Publish manifest for ${{ matrix.cassandra }}"
    needs: build-image
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cassandra: ["4.0.6", "3.11.13", "5.0-rc1"]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Login to Docker Hub
        uses: step-security/docker-login-action@6aa05fe688caf2c58e784663f01b3415ced503e8 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and push multi-arch manifest
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          IMAGE=shotover/cassandra-test:${{ matrix.cassandra }}-$TAG
          docker buildx imagetools create -t $IMAGE \
            $IMAGE-amd64 \
            $IMAGE-arm64
